# Generated by Django 4.0.3 on 2022-06-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0003_makeupcard_sessioncard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makeupcard',
            old_name='photo_session',
            new_name='photo_makeup',
        ),
    ]
