# Generated by Django 4.0.3 on 2022-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0006_rename_name_servicescard_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('heading', models.CharField(max_length=250)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories')),
                ('title', models.CharField(max_length=250)),
                ('category_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField()),
                ('product_reviews', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('social_icon', models.ImageField(blank=True, null=True, upload_to='footer')),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('copyright', models.TextField(max_length=300)),
            ],
        ),
    ]
