# Generated by Django 4.0.3 on 2022-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0007_banner_categories_featuredproduct_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescard',
            name='service_url',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
    ]
