# Generated by Django 4.0.3 on 2022-06-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0008_servicescard_service_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('HospitalityServices', models.CharField(choices=[('Yes', 'Yes'), ('No', ' No')], max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('hallto', models.CharField(blank=True, default='To Women and Man ', max_length=100, null=True)),
                ('Total_capacity', models.IntegerField()),
                ('Sound_system', models.CharField(choices=[('Yes', 'Yes'), ('No', ' No')], max_length=50)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('hallcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages_app.hallcard')),
            ],
        ),
    ]
