# Generated by Django 4.0.3 on 2022-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0009_detailshall'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailshall',
            name='name',
            field=models.CharField(default=4, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailshall',
            name='photo_hall',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
