# Generated by Django 4.0.3 on 2022-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0010_detailshall_name_detailshall_photo_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailshall',
            name='book_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/contact/', null=True),
        ),
    ]
