# Generated by Django 4.0.3 on 2022-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0012_contact_date_contact_hall_card_contact_makeup_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallcard',
            name='HospitalityServices',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', ' No')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='Sound_system',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', ' No')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='Total_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='book_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/contact/', null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='hallto',
            field=models.CharField(blank=True, default='To Women and Man ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='hallcard',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hallcard',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='DetailsHall',
        ),
    ]
