# Generated by Django 4.0.3 on 2022-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0013_hallcard_hospitalityservices_hallcard_sound_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncard',
            name='Photographer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sessioncard',
            name='Photography_Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioncard',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sessioncard',
            name='book_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/contact/', null=True),
        ),
        migrations.AddField(
            model_name='sessioncard',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioncard',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
