# Generated by Django 4.0.3 on 2022-06-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0015_remove_sessioncard_photography_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallcard',
            name='category',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='pages_app.categories'),
        ),
        migrations.AddField(
            model_name='makeupcard',
            name='category',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='pages_app.categories'),
        ),
        migrations.AddField(
            model_name='sessioncard',
            name='category',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='pages_app.categories'),
        ),
    ]
