# Generated by Django 4.0.3 on 2022-06-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0019_alter_hallcard_category_alter_makeupcard_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='makeupcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sessioncard',
            name='category',
        ),
    ]
