# Generated by Django 4.0.3 on 2022-06-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0020_remove_hallcard_category_remove_makeupcard_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncard',
            name='category',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages_app.categories'),
        ),
    ]
